### ISSUE TITLE
Doesn't work with wp_dropdown_users_args()

### ISSUE THREAD

**Issue by SukcesStrony** [WebDevStudios/WDS-Dynamic-Dropdowns#5]
Would be great if this worked with the code that lets you limit user roles which should be included in the search, like the WP core does:

if(!function_exists('ss_add_subscribers_to_dropdown')){
    add_filter( 'wp_dropdown_users_args', 'ss_add_subscribers_to_dropdown', 10, 2 );

```
function ss_add_subscribers_to_dropdown( $query_args, $r ) {
  $query_args['who'] = '';
  return $query_args;
}
```

}

**Comment by mmcachran** [comment]
The user query args are now updated to use wp_dropdown_users_args.
